version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    container_name: maestro_database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=maestros
